=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/xml/012_EVASQM_EMartinez_24MAY22/PGTA2/PGTA2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="prensa">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="diario" minOccurs="1" maxOccurs="5">
                        <xs:complexType>
                          <xs:all>
                          <xs:element type="xs:string" name="nombre"/>
                          <xs:element name="codigo">
                                   <xs:simpleType>
                                       <xs:restriction base="xs:integer">
                                          <xs:minInclusive value="1000"/>
                                         <xs:maxInclusive value="2000"/>
                                     </xs:restriction>
                                  </xs:simpleType>
                        </xs:element>
                        <xs:element type="xs:date" name="fecha"/>
                        <xs:element type="xs:string" name="publicado"/>
                        <xs:element name="clasificacion">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                <xs:attribute name="perfil_politico" use="optional">
                                 <xs:simpleType>
                                <xs:restriction base="xs:string">
                            <xs:pattern value="Derecha|Centro|Izquierda"/>
                           </xs:restriction>
                           </xs:simpleType>
                           </xs:attribute>
                        </xs:extension>
                        </xs:simpleContent>
                        </xs:complexType>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          </xs:element>
    </xs:schema>

=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/xml/012_EVASQM_EMartinez_24MAY22/PGTA2/PGTA2.xml
<?xml version="1.0"?>
<prensa   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="pgta2.xsd"> 

	 <diario>
      <nombre>ABC</nombre>
      <codigo>1515</codigo>
	  <fecha>2022-05-23</fecha>
	  <publicado>true</publicado>
	  <clasificacion  perfil_politico="Derecha"/>  
	 </diario>
	
	<diario>
	   <codigo>1414</codigo>
	   <fecha>2022-05-24</fecha>
       <nombre>El Pais</nombre>
	   <publicado>true</publicado>
	   <clasificacion perfil_politico="Izquierda"/> 
	 </diario>


    <diario>
      <fecha>2022-04-30</fecha>
      <codigo>1616</codigo>
	   <nombre>La Razon</nombre>
	   <publicado>false</publicado>
	   <clasificacion perfil_politico="Centro" />
	 </diario>

</prensa>
