<?xml version="1.0" encoding="UTF-8"?>
<!-- Ejercicio: PR3_002.xml -->
<!DOCTYPE agenda [
  <!ELEMENT agenda (contacto, contacto)>
  <!ELEMENT contacto (nombre, telefonoFijo, telefonoMovil+)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT telefonoFijo (#PCDATA)>
  <!ELEMENT telefonoMovil (#PCDATA)> 
]>

<agenda>
  <contacto>
    <nombre>Ayuntamiento</nombre>
    <telefonoFijo>010</telefonoFijo>
    <telefonoMovil>Desconocido</telefonoMovil>
  </contacto>
  <contacto>
    <nombre>Emergencias</nombre>
    <telefonoFijo>112 (Union Europea)</telefonoFijo>
    <telefonoMovil>Desconocido</telefonoMovil>
  </contacto>
</agenda>


