=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/xml/Ejercicios/Ej5/05-001.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="catalogo">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="libro" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="titulo" type="xsd:string" minOccurs="1" maxOccurs="1"/>
              <xsd:element name="isbn" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
              <xsd:element name="autores" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="autor" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="paginas" type="xsd:integer" minOccurs="1" maxOccurs="unbounded"/>
              <xsd:element name="editorial" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/HTML/CSS/PR5 CSS3/PR51.xml
﻿<?xml version="1.0" encoding="UTF-8" ?>
 <!-- Ejemplo: PR05-001.xml --> 
<catalogo 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="05-001.xsd">
	<libro>
		<titulo>Manual Imprescindible de C/C++</titulo>
		<isbn>9788441526143</isbn>
		<autores>
			<autor>Miguel Angel Acera Garcia</autor>
		</autores>
		<paginas>416</paginas>
		<editorial>Anaya Multimedia</editorial>
	</libro>
	<libro>
		<titulo>Redes locales</titulo>
		<isbn>9788441519800</isbn>
		<autores>
			<autor>Jim Doherty</autor>
			<autor>Neil Anderson</autor>
		</autores>
		<paginas>544</paginas>
		<editorial>Anaya Multimedia</editorial>
	</libro>
</catalogo>
