=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/xml/Ejercicios/Ej5/A05-002.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="coleccion">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="objeto" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="nombre" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="numero" type="xsd:integer" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="fecha" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
          </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/xml/drive-download-20220524T151837Z-001/PR5-002.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!-- Ejercicio: PR05-002.xml --> 
<coleccion 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="A05-002.xsd"> 
   <objeto>
       <nombre>Moneda</nombre>
       <numero>7483</numero>
       <fecha>1916-08-02</fecha>
   </objeto>
    <objeto>
       <nombre>Periódico</nombre>
       <numero>4355</numero>
       <fecha>1958-10-30</fecha>
   </objeto>
</coleccion>
