=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/xml/Ejercicios/Ej5/PR5-004_rpta.xsd
﻿<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	   <xsd:element name="galeria">
       <xsd:complexType>
              <xsd:sequence>
                   <xsd:element name="cuadro" >
					            <xsd:complexType>
						           <xsd:sequence>
							             <xsd:element name="titulo" type="xsd:string" />
							             <xsd:element name="referencia"  />
					                 <xsd:element name="autor" type="xsd:string"   />
						          </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
              </xsd:sequence>
      </xsd:complexType>
	  </xsd:element>
</xsd:schema>

=== EnriqueMartinezFerrer/Desarrollo-de-Aplicacones-Multiplataforma-DAM/DAM1/HTML/HTML/CSS/PR5 CSS3/PR54.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Ejercicio5: - PR05-004.xml -->
<galeria
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="PR5-004_rpta.xsd">
   <cuadro>
       <titulo> El atardecer</titulo>
       <referencia>475</referencia>
    </cuadro>
    <cuadro>
      <titulo> La noche</titulo>
       <referencia>396</referencia>
       <autor>Ricardo</autor>
   </cuadro>
</galeria>
